name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@v6.1
      env:
        PRIVATE_KEY: ${{ secrets.CORONAKEY }}
        HOST: dokku@157.230.195.60
        PROJECT: coronatrend